export const allDistricts = [
  "Ampara",
  "Anuradhapura",
  "Batticaloa",
  "Badulla",
  "Colombo",
  "Galle",
  "Gampaha",
  "Hambantota",
  "Jaffna",
  "Kalutara",
  "Kandy",
  "Kegalle",
  "Kilinochchi",
  "Kurunegala",
  "Mannar",
  "Matara",
  "Matale",
  "Monaragala",
  "Mullaitivu",
  "Nuwara Eliya",
  "Puttalam",
  "Polonnaruwa",
  "Ratnapura",
  "Trincomalee",
  "Vavuniya",
];

export const LUNGS = [
  {
    color: "#4DFF02",
    image: "/lungs/1.png",
  },
  {
    color: "#AFFF02",
    image: "/lungs/2.png",
  },
  {
    color: "#DAFF02",
    image: "/lungs/3.png",
  },
  {
    color: "#FFE002",
    image: "/lungs/4.png",
  },
  {
    color: "#FFC72C",
    image: "/lungs/5.png",
  },
  {
    color: "#FF8B02",
    image: "/lungs/6.png",
  },
  {
    color: "#FF5D02",
    image: "/lungs/7.png",
  },
  {
    color: "#FF1A02",
    image: "/lungs/8.png",
  },
];

export const initialStateDistrictGraph = {
  Ampara: 0,
  Anuradhapura: 0,
  Batticaloa: 0,
  Badulla: 0,
  Colombo: 0,
  Galle: 0,
  Gampaha: 0,
  Hambantota: 0,
  Jaffna: 0,
  Kalutara: 0,
  Kandy: 0,
  Kegalle: 0,
  Kilinochchi: 0,
  Kurunegala: 0,
  Mannar: 0,
  Matale: 0,
  Matara: 0,
  Moneragala: 0,
  Mullaitivu: 0,
  NuwaraEliya: 0,
  Polonnaruwa: 0,
  Puttalam: 0,
  Ratnapura: 0,
  Trincomalee: 0,
  Vavuniya: 0,
};
